[package]
name = "presenterm"
authors = ["Matias Fontanini"]
description = "A terminal slideshow presentation tool"
repository = "https://github.com/mfontanini/presenterm"
license = "BSD-2-Clause"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
comrak = { version = "0.19", default-features = false }
crossterm = { version = "0.27", features = ["serde"] }
merge-struct = "0.1.0"
image = "0.24"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
sixel-sys = { git = "https://github.com/retpolanne/sixel-sys.git" }
syntect = "5.1"
thiserror = "1"
unicode-width = "0.1"
viuer = "0.7.1"

[dev-dependencies]
rstest = { version = "0.18", default-features = false }

[features]
default = []
sixel = ["viuer/sixel"]
